import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Brain,
  Download,
  Github,
  Heart,
  Mic,
  PauseCircle,
  RotateCcw,
  Save,
  Square,
  Volume2
} from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { speakGuidance } from "../ai/piper";
import { generateReflection } from "../ai/reflectionClient";
import { transcribeWithWhisper } from "../ai/transcriptionClient";
import { BilateralAudioEngine } from "../audio/bilateralAudio";
import { RecordingController, type RecordingResult } from "../audio/recording";
import { blobToMonoFloat32, encodePcmWav } from "../audio/wav";
import {
  clearSessions,
  deleteSession,
  listSessions,
  saveSession
} from "../storage/sessionRepository";
import { APP_VERSION, COMMIT_SHA, LIVE_URL, PAYPAL_URL, REPOSITORY_URL } from "../../shared/meta";
import { useToast } from "../../shared/toast";
import { assessPace, formatDuration } from "./sessionLogic";
import type { DistressRating, Guidance, SessionEvent, SessionPhase, ToneSettings } from "./sessionTypes";
import { ConsentPanel } from "./components/ConsentPanel";
import { SavedSessionsPanel } from "./components/SavedSessionsPanel";
import { SessionTimeline } from "./components/SessionTimeline";
import { ToneControls } from "./components/ToneControls";

const DEFAULT_TONE: ToneSettings = {
  frequency: 440,
  intervalMs: 650,
  volume: 0.05,
  wave: "sine"
};

const PHASE_LABELS: Record<SessionPhase, string> = {
  settle: "Settle",
  record: "Record",
  pause: "Pause",
  revisit: "Revisit",
  close: "Close"
};

export function SessionApp() {
  const { notify } = useToast();
  const queryClient = useQueryClient();
  const [consent, setConsent] = useState({ headphones: false, privacy: false, safety: false });
  const [phase, setPhase] = useState<SessionPhase>("settle");
  const [toneSettings, setToneSettings] = useState<ToneSettings>(DEFAULT_TONE);
  const [isTonePlaying, setIsTonePlaying] = useState(false);
  const [recording, setRecording] = useState(false);
  const [recordingResult, setRecordingResult] = useState<RecordingResult | null>(null);
  const [elapsedSeconds, setElapsedSeconds] = useState(0);
  const [transcript, setTranscript] = useState("");
  const [guidance, setGuidance] = useState<Guidance | null>(null);
  const [guidanceSource, setGuidanceSource] = useState<"local-rules" | "web-llm" | null>(null);
  const [distress, setDistress] = useState<DistressRating>({ before: 4, now: 4, after: 3 });
  const [events, setEvents] = useState<SessionEvent[]>([]);
  const [lastPauseSecond, setLastPauseSecond] = useState(0);
  const [useWebLlm, setUseWebLlm] = useState(false);
  const [allowSystemSpeech, setAllowSystemSpeech] = useState(false);
  const engineRef = useRef<BilateralAudioEngine | null>(null);
  const recorderRef = useRef<RecordingController | null>(null);
  const recordingStartedAt = useRef<number | null>(null);

  const canStart = consent.headphones && consent.privacy && consent.safety;
  const sessionDuration = recording ? elapsedSeconds : (recordingResult?.durationSeconds ?? elapsedSeconds);
  const pauseCount = events.filter((event) => event.type === "pause").length;
  const metrics = useMemo(
    () =>
      assessPace({
        transcript,
        durationSeconds: Math.max(sessionDuration, 1),
        pauseCount,
        secondsSincePause: Math.max(sessionDuration - lastPauseSecond, 0),
        distressBefore: distress.before,
        distressNow: distress.now
      }),
    [distress.before, distress.now, lastPauseSecond, pauseCount, sessionDuration, transcript]
  );

  const savedSessionsQuery = useQuery({
    queryKey: ["saved-sessions"],
    queryFn: listSessions
  });

  const reflectionMutation = useMutation({
    mutationFn: () =>
      generateReflection({
        transcript,
        phase,
        metrics,
        useWebLlm
      }),
    onSuccess: (result) => {
      setGuidance(result.guidance);
      setGuidanceSource(result.source);
      setPhase(result.guidance.recommendedPhase);
      addEvent("reflection", `Reflection generated by ${result.source}`);
    },
    onError: () => notify("Reflection could not be generated locally.", "error")
  });

  const transcriptionMutation = useMutation({
    mutationFn: async () => {
      if (!recordingResult) {
        throw new Error("Record audio before transcription.");
      }
      const decoded = await blobToMonoFloat32(recordingResult.blob);
      return transcribeWithWhisper(decoded);
    },
    onSuccess: (result) => {
      setTranscript((current) => [current.trim(), result.text].filter(Boolean).join("\n\n"));
      notify(`Local Whisper transcript added with ${result.model}.`, "success");
    },
    onError: () => notify("Whisper could not transcribe locally in this browser.", "warning")
  });

  useEffect(() => {
    engineRef.current = new BilateralAudioEngine(DEFAULT_TONE);
    recorderRef.current = new RecordingController();

    return () => {
      void engineRef.current?.dispose();
    };
  }, []);

  useEffect(() => {
    engineRef.current?.update(toneSettings);
  }, [toneSettings]);

  useEffect(() => {
    if (!recording) {
      return;
    }
    const timer = window.setInterval(() => {
      if (recordingStartedAt.current) {
        setElapsedSeconds((performance.now() - recordingStartedAt.current) / 1_000);
      }
    }, 250);

    return () => window.clearInterval(timer);
  }, [recording]);

  function addEvent(type: SessionEvent["type"], label: string) {
    setEvents((current) => [
      ...current,
      {
        id: crypto.randomUUID(),
        at: new Date().toISOString(),
        label,
        type
      }
    ]);
  }

  async function startTone() {
    try {
      await engineRef.current?.start(toneSettings);
      setIsTonePlaying(true);
      addEvent("tone", "Bilateral tones started");
    } catch {
      notify("Audio could not start. Check browser audio permissions.", "error");
    }
  }

  function stopTone() {
    engineRef.current?.stop();
    setIsTonePlaying(false);
    addEvent("tone", "Bilateral tones stopped");
  }

  async function startRecording() {
    try {
      await recorderRef.current?.start();
      recordingStartedAt.current = performance.now();
      setRecordingResult(null);
      setRecording(true);
      setPhase("record");
      addEvent("recording", "Recording started");
    } catch {
      notify("Microphone access was not available.", "error");
    }
  }

  async function stopRecording() {
    try {
      const result = await recorderRef.current?.stop();
      if (result) {
        setRecordingResult(result);
        setElapsedSeconds(result.durationSeconds);
      }
      setRecording(false);
      recordingStartedAt.current = null;
      addEvent("recording", "Recording stopped");
    } catch {
      notify("Recording could not be stopped cleanly.", "error");
    }
  }

  function markPause() {
    setPhase("pause");
    setLastPauseSecond(sessionDuration);
    addEvent("pause", "Pause marked");
  }

  async function saveCurrentSession() {
    try {
      await saveSession({
        transcript,
        guidance: guidance ?? undefined,
        durationSeconds: sessionDuration,
        distress,
        toneSettings,
        events
      });
      addEvent("save", "Private session saved");
      notify("Saved in this browser only.", "success");
      await queryClient.invalidateQueries({ queryKey: ["saved-sessions"] });
    } catch {
      notify("The session could not be saved locally.", "error");
    }
  }

  async function downloadWav() {
    if (!recordingResult) {
      notify("Record audio before exporting WAV.", "warning");
      return;
    }
    try {
      const decoded = await blobToMonoFloat32(recordingResult.blob);
      const wav = encodePcmWav(decoded.samples, decoded.sampleRate);
      const url = URL.createObjectURL(wav);
      const link = document.createElement("a");
      link.href = url;
      link.download = `bilateral-memory-session-${new Date().toISOString()}.wav`;
      link.click();
      URL.revokeObjectURL(url);
    } catch {
      notify("WAV export was not available for this recording.", "error");
    }
  }

  async function speakCurrentGuidance() {
    if (!guidance) {
      notify("Generate a reflection before speaking guidance.", "warning");
      return;
    }
    try {
      const source = await speakGuidance(
        [guidance.headline, guidance.body, ...guidance.prompts].join(". "),
        { allowSystemFallback: allowSystemSpeech }
      );
      notify(source === "piper" ? "Piper is speaking locally." : "System speech fallback started.", "success");
    } catch {
      notify("Piper voice guidance could not start in this browser.", "warning");
    }
  }

  async function resetSession() {
    stopTone();
    if (recording) {
      await stopRecording();
    }
    setPhase("settle");
    setRecordingResult(null);
    setElapsedSeconds(0);
    setTranscript("");
    setGuidance(null);
    setGuidanceSource(null);
    setDistress({ before: 4, now: 4, after: 3 });
    setEvents([]);
    setLastPauseSecond(0);
  }

  return (
    <main className="min-h-screen bg-paper text-ink" data-testid="app-shell">
      <div className="mx-auto grid w-full max-w-7xl gap-5 px-4 py-5 lg:grid-cols-[1fr_360px] lg:px-6">
        <div className="grid gap-5">
          <header className="rounded-lg border border-ink/10 bg-white p-5 shadow-quiet">
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <p className="text-sm font-semibold uppercase tracking-wide text-ember">
                  Private browser session
                </p>
                <h1 className="mt-2 max-w-3xl text-4xl font-semibold leading-tight md:text-5xl">
                  Bilateral Memory Processing
                </h1>
                <p className="mt-3 max-w-3xl leading-7 text-ink/70">
                  EMDR-inspired audio journaling with local recording, local prompts, and no trauma
                  upload path.
                </p>
              </div>
              <div className="grid gap-2 text-sm">
                <a
                  className="inline-flex items-center gap-2 rounded-lg border border-ink/15 px-3 py-2 font-semibold hover:bg-ink hover:text-white"
                  data-testid="repo-link"
                  href={REPOSITORY_URL}
                  rel="noreferrer"
                  target="_blank"
                >
                  <Github aria-hidden="true" size={16} />
                  Star on GitHub
                </a>
                <a
                  className="inline-flex items-center gap-2 rounded-lg border border-ember/30 px-3 py-2 font-semibold text-ember hover:bg-ember hover:text-white"
                  data-testid="paypal-link"
                  href={PAYPAL_URL}
                  rel="noreferrer"
                  target="_blank"
                >
                  <Heart aria-hidden="true" size={16} />
                  Support on PayPal
                </a>
              </div>
            </div>
          </header>

          <div className="grid gap-5 xl:grid-cols-[360px_1fr]">
            <ConsentPanel
              headphones={consent.headphones}
              privacy={consent.privacy}
              safety={consent.safety}
              onChange={(key, value) => setConsent((current) => ({ ...current, [key]: value }))}
            />

            <ToneControls
              canStart={canStart}
              isPlaying={isTonePlaying}
              onChange={setToneSettings}
              onStart={() => void startTone()}
              onStop={stopTone}
              settings={toneSettings}
            />
          </div>

          <section className="rounded-lg border border-ink/10 bg-white p-4 shadow-quiet">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div>
                <h2 className="text-lg font-semibold">Guided session</h2>
                <p className="mt-1 text-sm text-ink/60">
                  Phase: <span className="font-semibold text-ink">{PHASE_LABELS[phase]}</span> ·{" "}
                  Duration: {formatDuration(sessionDuration)}
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <button
                  className="inline-flex items-center gap-2 rounded-lg bg-tide px-3 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-tide/30"
                  disabled={!canStart || recording}
                  onClick={() => void startRecording()}
                  type="button"
                >
                  <Mic aria-hidden="true" size={16} />
                  Record
                </button>
                <button
                  className="inline-flex items-center gap-2 rounded-lg border border-ink/15 px-3 py-2 text-sm font-semibold disabled:opacity-40"
                  disabled={!recording}
                  onClick={() => void stopRecording()}
                  type="button"
                >
                  <Square aria-hidden="true" size={16} />
                  Stop
                </button>
                <button
                  className="inline-flex items-center gap-2 rounded-lg border border-saffron/50 px-3 py-2 text-sm font-semibold text-ink"
                  onClick={markPause}
                  type="button"
                >
                  <PauseCircle aria-hidden="true" size={16} />
                  Pause
                </button>
              </div>
            </div>

            <div className="mt-5 grid gap-4 lg:grid-cols-3">
              <label className="grid gap-2 text-sm font-medium">
                Before {distress.before}/10
                <input
                  aria-label="Distress before"
                  className="accent-moss"
                  max={10}
                  min={0}
                  onChange={(event) =>
                    setDistress((current) => ({ ...current, before: Number(event.target.value) }))
                  }
                  type="range"
                  value={distress.before}
                />
              </label>
              <label className="grid gap-2 text-sm font-medium">
                Now {distress.now}/10
                <input
                  aria-label="Distress now"
                  className="accent-ember"
                  max={10}
                  min={0}
                  onChange={(event) =>
                    setDistress((current) => ({ ...current, now: Number(event.target.value) }))
                  }
                  type="range"
                  value={distress.now}
                />
              </label>
              <label className="grid gap-2 text-sm font-medium">
                After {distress.after}/10
                <input
                  aria-label="Distress after"
                  className="accent-tide"
                  max={10}
                  min={0}
                  onChange={(event) =>
                    setDistress((current) => ({ ...current, after: Number(event.target.value) }))
                  }
                  type="range"
                  value={distress.after}
                />
              </label>
            </div>

            <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_280px]">
              <label className="grid gap-2 text-sm font-medium">
                Transcript or private notes
                <textarea
                  className="min-h-44 resize-y rounded-lg border border-ink/15 bg-paper/60 p-3 text-base leading-7 outline-none focus:border-tide focus:ring-2 focus:ring-tide/20"
                  data-testid="manual-transcript"
                  onChange={(event) => setTranscript(event.target.value)}
                  placeholder="Speak into the recorder, run local Whisper, or type only what you want to process."
                  value={transcript}
                />
              </label>
              <div className="grid gap-3 rounded-lg border border-ink/10 bg-paper/60 p-3">
                <Metric label="Words/min" value={metrics.wordsPerMinute.toString()} />
                <Metric label="Words" value={metrics.words.toString()} />
                <Metric label="Pace status" value={metrics.status} />
                <Metric label="Pauses" value={metrics.pauseCount.toString()} />
              </div>
            </div>

            <div className="mt-4 flex flex-wrap gap-2">
              <button
                className="inline-flex items-center gap-2 rounded-lg border border-ink/15 px-3 py-2 text-sm font-semibold disabled:opacity-40"
                disabled={!recordingResult || transcriptionMutation.isPending}
                onClick={() => transcriptionMutation.mutate()}
                type="button"
              >
                <Brain aria-hidden="true" size={16} />
                {transcriptionMutation.isPending ? "Transcribing..." : "Local Whisper"}
              </button>
              <button
                className="inline-flex items-center gap-2 rounded-lg bg-ink px-3 py-2 text-sm font-semibold text-white disabled:bg-ink/30"
                data-testid="generate-reflection"
                disabled={reflectionMutation.isPending}
                onClick={() => reflectionMutation.mutate()}
                type="button"
              >
                <Brain aria-hidden="true" size={16} />
                {reflectionMutation.isPending ? "Reflecting..." : "Generate reflection"}
              </button>
              <button
                className="inline-flex items-center gap-2 rounded-lg border border-ink/15 px-3 py-2 text-sm font-semibold"
                onClick={() => void speakCurrentGuidance()}
                type="button"
              >
                <Volume2 aria-hidden="true" size={16} />
                Piper voice
              </button>
              <button
                className="inline-flex items-center gap-2 rounded-lg border border-ink/15 px-3 py-2 text-sm font-semibold"
                onClick={() => void downloadWav()}
                type="button"
              >
                <Download aria-hidden="true" size={16} />
                WAV
              </button>
              <button
                className="inline-flex items-center gap-2 rounded-lg border border-moss/40 px-3 py-2 text-sm font-semibold text-moss"
                onClick={() => void saveCurrentSession()}
                type="button"
              >
                <Save aria-hidden="true" size={16} />
                Save local
              </button>
              <button
                className="inline-flex items-center gap-2 rounded-lg border border-ember/30 px-3 py-2 text-sm font-semibold text-ember"
                onClick={() => void resetSession()}
                type="button"
              >
                <RotateCcw aria-hidden="true" size={16} />
                Reset
              </button>
            </div>

            <div className="mt-4 grid gap-3 md:grid-cols-2">
              <label className="flex items-center gap-2 text-sm text-ink/70">
                <input
                  checked={useWebLlm}
                  className="h-4 w-4 accent-tide"
                  onChange={(event) => setUseWebLlm(event.target.checked)}
                  type="checkbox"
                />
                Try WebLLM when this browser supports it
              </label>
              <label className="flex items-center gap-2 text-sm text-ink/70">
                <input
                  checked={allowSystemSpeech}
                  className="h-4 w-4 accent-tide"
                  onChange={(event) => setAllowSystemSpeech(event.target.checked)}
                  type="checkbox"
                />
                Allow system speech fallback if Piper cannot load
              </label>
            </div>
          </section>

          {guidance ? (
            <section
              className="rounded-lg border border-moss/25 bg-white p-5 shadow-quiet"
              data-testid="guidance-panel"
            >
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                  <p className="text-sm font-semibold uppercase tracking-wide text-moss">
                    {guidanceSource === "web-llm" ? "Local LLM" : "Local guide"}
                  </p>
                  <h2 className="mt-1 text-2xl font-semibold" data-testid="guidance-headline">
                    {guidance.headline}
                  </h2>
                </div>
                <span className="rounded-lg bg-paper px-3 py-2 text-sm font-semibold">
                  Next: {PHASE_LABELS[guidance.recommendedPhase]}
                </span>
              </div>
              <p className="mt-4 leading-7 text-ink/75">{guidance.body}</p>
              <ul className="mt-4 grid gap-2">
                {guidance.prompts.map((prompt) => (
                  <li className="rounded-lg border border-ink/10 p-3" key={prompt}>
                    {prompt}
                  </li>
                ))}
              </ul>
              {guidance.safetyNote ? (
                <p className="mt-4 rounded-lg border border-ember/30 bg-ember/5 p-3 text-sm leading-6 text-ember">
                  {guidance.safetyNote}
                </p>
              ) : null}
            </section>
          ) : null}
        </div>

        <aside className="grid content-start gap-5">
          <section className="rounded-lg border border-ink/10 bg-white p-4 shadow-quiet">
            <h2 className="text-lg font-semibold">Local-only status</h2>
            <div className="mt-3 grid gap-2 text-sm">
              <Status label="Audio" value={isTonePlaying ? "tones active" : "ready"} />
              <Status label="Recorder" value={recording ? "recording" : "standby"} />
              <Status label="Transcript" value={`${metrics.words} words`} />
              <Status label="Network" value="no session upload path" />
              <Status label="Live" value={LIVE_URL} />
            </div>
          </section>

          <SessionTimeline events={events} />
          <SavedSessionsPanel
            onClear={() => {
              void clearSessions().then(() => queryClient.invalidateQueries({ queryKey: ["saved-sessions"] }));
            }}
            onDelete={(id) => {
              void deleteSession(id).then(() =>
                queryClient.invalidateQueries({ queryKey: ["saved-sessions"] })
              );
            }}
            sessions={savedSessionsQuery.data ?? []}
          />

          <footer className="rounded-lg border border-ink/10 bg-white p-4 text-sm leading-6 text-ink/65 shadow-quiet">
            <p data-testid="version-commit">
              Version {APP_VERSION} · Commit {COMMIT_SHA}
            </p>
            <p className="mt-2">
              Source:{" "}
              <a className="font-semibold text-tide" href={REPOSITORY_URL} rel="noreferrer" target="_blank">
                {REPOSITORY_URL}
              </a>
            </p>
            <p className="mt-2">
              Support:{" "}
              <a className="font-semibold text-ember" href={PAYPAL_URL} rel="noreferrer" target="_blank">
                {PAYPAL_URL}
              </a>
            </p>
          </footer>
        </aside>
      </div>
    </main>
  );
}

function Metric({ label, value }: { readonly label: string; readonly value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-lg bg-white px-3 py-2">
      <span className="text-ink/60">{label}</span>
      <span className="font-semibold capitalize">{value}</span>
    </div>
  );
}

function Status({ label, value }: { readonly label: string; readonly value: string }) {
  return (
    <div className="grid gap-1 rounded-lg border border-ink/10 p-3">
      <span className="text-xs uppercase tracking-wide text-ink/45">{label}</span>
      <span className="break-words font-semibold text-ink">{value}</span>
    </div>
  );
}
